# Generated by Django 2.2.12 on 2020-09-29 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialGoal',
        ),
    ]
