# Generated by Django 2.2.12 on 2020-09-29 20:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0003_socialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialgoal',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
