# Generated by Django 2.2.12 on 2020-09-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal', '0004_socialgoal_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
